name: Test Plugin

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '1.24.0'
          cache: false
      - name: Test Java version resolution with vfox's Lua interpreter
        run: |
          go run github.com/yuin/gopher-lua/cmd/glua@v1.1.1 tests/pre_use_test.lua
          go run github.com/yuin/gopher-lua/cmd/glua@v1.1.1 tests/loongnix_test.lua
